import sys
import os

def compile_submission(worker_threshold=2, safety_buffer=2, output_path="submission.py"):
    # Ordered files
    files = [
        "cartographer.py",
        "pathfinder.py",
        "economy.py",
        "tactician.py",
        "orchestrator.py"
    ]
    
    compiled_lines = []
    
    # Prepend TACTICS_PARAMS
    compiled_lines.append("# Unified agent submission generated by compiler.py")
    compiled_lines.append(f"TACTICS_PARAMS = {{")
    compiled_lines.append(f"    'WORKER_THRESHOLD': {worker_threshold},")
    compiled_lines.append(f"    'SAFETY_BUFFER': {safety_buffer}")
    compiled_lines.append(f"}}")
    compiled_lines.append("")
    
    # Local imports to strip
    local_imports = [
        "from pathfinder import",
        "from economy import",
        "from tactician import",
        "from cartographer import"
    ]
    
    for filename in files:
        if not os.path.exists(filename):
            print(f"Error: {filename} not found!")
            return False
            
        compiled_lines.append(f"# === Start of {filename} ===")
        with open(filename, "r") as f:
            for line in f:
                # Strip local imports
                strip_line = False
                for imp in local_imports:
                    if line.strip().startswith(imp):
                        strip_line = True
                        break
                if strip_line:
                    continue
                compiled_lines.append(line.rstrip())
        compiled_lines.append(f"# === End of {filename} ===")
        compiled_lines.append("")
        
    # Append the agent wrapper
    wrapper = """
# Persistent agent state
player_cartographers = {}
controllers = {}

def agent(obs, config):
    player = obs.player
    if player not in player_cartographers:
        player_cartographers[player] = Cartographer(width=config.width, height=config.height)
        controllers[player] = TrafficController(enable_tactics=True)
        
    cartographer = player_cartographers[player]
    controller = controllers[player]
    cartographer.update(obs)
    
    return controller.process_turn(obs, cartographer, config)
"""
    compiled_lines.append(wrapper)
    
    # Write to output_path
    with open(output_path, "w") as f:
        f.write("\n".join(compiled_lines) + "\n")
        
    print(f"Successfully compiled {output_path} with WORKER_THRESHOLD={worker_threshold}, SAFETY_BUFFER={safety_buffer}")
    return True

if __name__ == "__main__":
    worker_t = 2
    safety_b = 2
    if len(sys.argv) > 1:
        worker_t = int(sys.argv[1])
    if len(sys.argv) > 2:
        safety_b = int(sys.argv[2])
        
    compile_submission(worker_t, safety_b)
