# Unified agent submission generated by compiler.py
TACTICS_PARAMS = {
    'WORKER_THRESHOLD': 2,
    'SAFETY_BUFFER': 2
}

# === Start of cartographer.py ===
class Cartographer:
    WALL_N = 1
    WALL_E = 2
    WALL_S = 4
    WALL_W = 8

    DIR_WALL_BIT = {
        "NORTH": WALL_N,
        "EAST": WALL_E,
        "SOUTH": WALL_S,
        "WEST": WALL_W
    }

    OPPOSITE_DIR = {
        "NORTH": "SOUTH",
        "SOUTH": "NORTH",
        "EAST": "WEST",
        "WEST": "EAST"
    }

    DIR_OFFSETS = {
        "NORTH": (0, 1),
        "SOUTH": (0, -1),
        "EAST": (1, 0),
        "WEST": (-1, 0)
    }

    def __init__(self, width=20, height=20):
        self.width = width
        self.height = height
        # Global map of walls: (col, row) -> wall_bitfield
        self.global_map = {}
        # Keep track of bounds
        self.south_bound = 0
        self.north_bound = height - 1

    def update(self, obs):
        """Update global map with observation data."""
        self.south_bound = obs.southBound
        self.north_bound = obs.northBound

        # obs.walls contains flat array from southBound to northBound
        # Index: (row - southBound) * width + col
        for idx, val in enumerate(obs.walls):
            if val != -1:
                col = idx % self.width
                row = self.south_bound + (idx // self.width)
                self.global_map[(col, row)] = val

    def get_wall(self, col, row):
        return self.global_map.get((col, row), -1)

    def is_wall(self, col, row, direction):
        """Check if there is a wall in the given direction from (col, row)."""
        bit = self.DIR_WALL_BIT.get(direction, 0)
        # Check source cell
        if (col, row) in self.global_map:
            if self.global_map[(col, row)] & bit:
                return True
        # Check target cell
        dc, dr = self.DIR_OFFSETS.get(direction, (0, 0))
        target_pos = (col + dc, row + dr)
        opp_dir = self.OPPOSITE_DIR.get(direction, "")
        opp_bit = self.DIR_WALL_BIT.get(opp_dir, 0)
        if target_pos in self.global_map:
            if self.global_map[target_pos] & opp_bit:
                return True
        return False

    def is_walkable(self, col, row, direction):
        """Check if we can move from (col, row) in the given direction based on mapped walls."""
        dc, dr = self.DIR_OFFSETS[direction]
        nc, nr = col + dc, row + dr
        if nc < 0 or nc >= self.width or nr < 0:
            return False
        return not self.is_wall(col, row, direction)

    def get_mapped_count(self):
        return len(self.global_map)
# === End of cartographer.py ===

# === Start of pathfinder.py ===
import heapq

SAFETY_BUFFER_PENALTY = 50

def project_south_bound(current_step, current_south, current_scroll_counter, future_turns, config):
    """
    Predicts the southBound value `future_turns` into the future.
    """
    def get_val(key, default):
        if hasattr(config, key):
            return getattr(config, key)
        if isinstance(config, dict) and key in config:
            return config[key]
        return default

    scroll_ramp_steps = get_val("scrollRampSteps", 400)
    scroll_start_interval = get_val("scrollStartInterval", 4)
    scroll_end_interval = get_val("scrollEndInterval", 1)

    def get_scroll_interval(step):
        if step >= scroll_ramp_steps:
            return scroll_end_interval
        progress = step / max(1, scroll_ramp_steps)
        interval = scroll_start_interval - (scroll_start_interval - scroll_end_interval) * progress
        return max(scroll_end_interval, round(interval))

    south = current_south
    counter = current_scroll_counter
    step = current_step

    for _ in range(future_turns):
        counter -= 1
        if counter <= 0:
            south += 1
            counter = get_scroll_interval(step)
        step += 1

    return south

def _safety_penalty(row, projected_south, safety_buffer):
    if row < projected_south:
        return None
    if safety_buffer > 0 and row < projected_south + safety_buffer:
        return SAFETY_BUFFER_PENALTY
    return 0

def _previous_distinct_position(start, path, current_pos):
    for pos in reversed([start] + path):
        if pos != current_pos:
            return pos
    return None

def find_reachable_paths(cartographer, start, current_step, current_south, current_scroll_counter, move_period, config, max_depth=20, initial_jump_cd=None, safety_buffer=0, blocked_cells=None):
    """
    Performs a BFS from start to find all reachable cells within max_depth steps.
    It takes scroll-awareness into account, and is jump-aware for the Factory.
    Returns:
        dictionary mapping target cell (col, row) -> path (list of nodes from start to target, excluding start)
    """
    projected_south_cache = {}
    def get_projected_south(turns):
        if turns not in projected_south_cache:
            projected_south_cache[turns] = project_south_bound(
                current_step, current_south, current_scroll_counter, turns, config
            )
        return projected_south_cache[turns]

    if initial_jump_cd is not None:
        queue = [(0, 0, start[0], start[1], [], initial_jump_cd)]
        visited_states = {(start[0], start[1], initial_jump_cd): 0}
    else:
        queue = [(0, 0, start[0], start[1], [])]
        visited_states = {start: 0}

    paths = {start: []}
    path_costs = {start: 0}

    heapq.heapify(queue)
    while queue:
        if initial_jump_cd is not None:
            cost, steps, c, r, path, jump_cd = heapq.heappop(queue)
            state_key = (c, r, jump_cd)
        else:
            cost, steps, c, r, path = heapq.heappop(queue)
            jump_cd = None
            state_key = (c, r)

        if cost > visited_states.get(state_key, float('inf')):
            continue

        if len(path) >= max_depth:
            continue

        previous_pos = _previous_distinct_position(start, path, (c, r))

        # 1. Standard adjacent walking transitions
        for direction, offset in cartographer.DIR_OFFSETS.items():
            if cartographer.is_walkable(c, r, direction):
                nc, nr = c + offset[0], r + offset[1]
                n_pos = (nc, nr)

                if n_pos == previous_pos:
                    continue

                next_steps = steps + 1
                next_turns = next_steps * move_period
                projected_south = get_projected_south(next_turns)

                penalty = _safety_penalty(nr, projected_south, safety_buffer)
                if penalty is None or nr > cartographer.north_bound:
                    continue

                if blocked_cells and n_pos in blocked_cells:
                    continue

                next_cost = cost + move_period + penalty

                if initial_jump_cd is not None:
                    next_jump_cd = max(0, jump_cd - move_period)
                    state = (nc, nr, next_jump_cd)
                    if next_cost < visited_states.get(state, float('inf')):
                        visited_states[state] = next_cost
                        next_path = path + [n_pos]
                        if next_cost < path_costs.get(n_pos, float('inf')):
                            paths[n_pos] = next_path
                            path_costs[n_pos] = next_cost
                        heapq.heappush(queue, (next_cost, next_steps, nc, nr, next_path, next_jump_cd))
                else:
                    if next_cost < visited_states.get(n_pos, float('inf')):
                        visited_states[n_pos] = next_cost
                        next_path = path + [n_pos]
                        if next_cost < path_costs.get(n_pos, float('inf')):
                            paths[n_pos] = next_path
                            path_costs[n_pos] = next_cost
                        heapq.heappush(queue, (next_cost, next_steps, nc, nr, next_path))

        # 3. Wait transition (stay in place to cool down jump)
        if initial_jump_cd is not None and jump_cd > 0:
            next_col = c
            next_row = r
            next_steps = steps + 1
            next_turns = next_steps * move_period
            projected_south = get_projected_south(next_turns)
            penalty = _safety_penalty(next_row, projected_south, safety_buffer)
            if penalty is not None:
                next_jump_cd = max(0, jump_cd - move_period)
                state = (next_col, next_row, next_jump_cd)
                next_cost = cost + move_period + penalty
                if next_cost < visited_states.get(state, float('inf')):
                    visited_states[state] = next_cost
                    heapq.heappush(queue, (next_cost, next_steps, next_col, next_row, path + [(next_col, next_row)], next_jump_cd))

        # 2. Jump transitions (ignoring intermediate walls)
        if initial_jump_cd is not None and jump_cd == 0:
            for direction, offset in cartographer.DIR_OFFSETS.items():
                nc, nr = c + offset[0] * 2, r + offset[1] * 2
                n_pos = (nc, nr)

                if nc < 0 or nc >= cartographer.width or nr < 0:
                    continue

                next_steps = steps + 1
                next_turns = next_steps * move_period
                projected_south = get_projected_south(next_turns)

                penalty = _safety_penalty(nr, projected_south, safety_buffer)
                if penalty is None or nr > cartographer.north_bound:
                    continue

                if blocked_cells and n_pos in blocked_cells:
                    continue

                next_jump_cd = 20
                state = (nc, nr, next_jump_cd)
                next_cost = cost + move_period + penalty
                if next_cost < visited_states.get(state, float('inf')):
                    visited_states[state] = next_cost
                    next_path = path + [n_pos]
                    if next_cost < path_costs.get(n_pos, float('inf')):
                        paths[n_pos] = next_path
                        path_costs[n_pos] = next_cost
                    heapq.heappush(queue, (next_cost, next_steps, nc, nr, next_path, next_jump_cd))

    return paths

def find_path(cartographer, start, target, current_step, current_south, current_scroll_counter, move_period, config, initial_jump_cd=None, safety_buffer=0, blocked_cells=None):
    """
    Finds the shortest path from start (col, row) to target (col, row) using A* search.
    The path is scroll-aware and jump-aware.
    """
    if start == target:
        return []

    projected_south_cache = {}
    def get_projected_south(turns):
        if turns not in projected_south_cache:
            projected_south_cache[turns] = project_south_bound(
                current_step, current_south, current_scroll_counter, turns, config
            )
        return projected_south_cache[turns]

    def heuristic(pos):
        return abs(pos[0] - target[0]) + abs(pos[1] - target[1])

    if initial_jump_cd is not None:
        start_h = heuristic(start)
        open_set = [(start_h * move_period, 0, 0, start[0], start[1], [], initial_jump_cd)]
        visited = {(start[0], start[1], initial_jump_cd): 0}
    else:
        start_h = heuristic(start)
        open_set = [(start_h * move_period, 0, 0, start[0], start[1], [])]
        visited = {start: 0}

    while open_set:
        if initial_jump_cd is not None:
            f, cost, turns, col, row, path, jump_cd = heapq.heappop(open_set)
        else:
            f, cost, turns, col, row, path = heapq.heappop(open_set)
            jump_cd = None

        if (col, row) == target:
            return path

        state_key = (col, row, jump_cd) if initial_jump_cd is not None else (col, row)
        if cost > visited.get(state_key, float('inf')):
            continue

        previous_pos = _previous_distinct_position(start, path, (col, row))

        # 1. Standard walking moves
        for direction, offset in cartographer.DIR_OFFSETS.items():
            if cartographer.is_walkable(col, row, direction):
                nc, nr = col + offset[0], row + offset[1]
                n_pos = (nc, nr)

                if n_pos == previous_pos:
                    continue

                next_turns = turns + move_period
                projected_south = get_projected_south(next_turns)

                penalty = _safety_penalty(nr, projected_south, safety_buffer)
                if penalty is None or nr > cartographer.north_bound:
                    continue

                if blocked_cells and n_pos in blocked_cells and n_pos != target:
                    continue

                next_cost = cost + move_period + penalty

                if initial_jump_cd is not None:
                    next_jump_cd = max(0, jump_cd - move_period)
                    visited_key = (nc, nr, next_jump_cd)
                    if next_cost < visited.get(visited_key, float('inf')):
                        visited[visited_key] = next_cost
                        next_f = next_cost + heuristic(n_pos) * move_period
                        heapq.heappush(open_set, (next_f, next_cost, next_turns, nc, nr, path + [n_pos], next_jump_cd))
                else:
                    visited_key = n_pos
                    if next_cost < visited.get(visited_key, float('inf')):
                        visited[visited_key] = next_cost
                        next_f = next_cost + heuristic(n_pos) * move_period
                        heapq.heappush(open_set, (next_f, next_cost, next_turns, nc, nr, path + [n_pos]))

        # 2. Jump moves (only for jump-capable pathfinding when cooldown is 0)
        if initial_jump_cd is not None and jump_cd == 0:
            for direction, offset in cartographer.DIR_OFFSETS.items():
                nc, nr = col + offset[0] * 2, row + offset[1] * 2
                n_pos = (nc, nr)

                if nc < 0 or nc >= cartographer.width or nr < 0:
                    continue

                next_turns = turns + move_period
                projected_south = get_projected_south(next_turns)

                penalty = _safety_penalty(nr, projected_south, safety_buffer)
                if penalty is None or nr > cartographer.north_bound:
                    continue

                if blocked_cells and n_pos in blocked_cells and n_pos != target:
                    continue

                next_jump_cd = 20
                visited_key = (nc, nr, next_jump_cd)
                next_cost = cost + move_period + penalty
                if next_cost < visited.get(visited_key, float('inf')):
                    visited[visited_key] = next_cost
                    next_f = next_cost + heuristic(n_pos) * move_period
                    heapq.heappush(open_set, (next_f, next_cost, next_turns, nc, nr, path + [n_pos], next_jump_cd))

        # 3. Wait transition (stay in place to cool down jump)
        if initial_jump_cd is not None and jump_cd > 0:
            next_col = col
            next_row = row
            next_turns = turns + move_period
            projected_south = get_projected_south(next_turns)
            penalty = _safety_penalty(next_row, projected_south, safety_buffer)
            if penalty is not None:
                next_jump_cd = max(0, jump_cd - move_period)
                visited_key = (next_col, next_row, next_jump_cd)
                next_cost = cost + move_period + penalty
                if next_cost < visited.get(visited_key, float('inf')):
                    visited[visited_key] = next_cost
                    next_f = next_cost + heuristic((next_col, next_row)) * move_period
                    heapq.heappush(open_set, (next_f, next_cost, next_turns, next_col, next_row, path + [(next_col, next_row)], next_jump_cd))

    return None
# === End of pathfinder.py ===

# === Start of economy.py ===

class MacroManager:
    def __init__(self):
        self.remembered_nodes = set()

    def update(self, obs):
        """Update macro manager state at the beginning of each turn."""
        self.update_nodes(obs)

    def update_nodes(self, obs):
        """Update the set of remembered mining nodes based on visibility and status."""
        # Add currently visible mining nodes
        for key in obs.miningNodes.keys():
            try:
                col, row = map(int, key.split(","))
                self.remembered_nodes.add((col, row))
            except ValueError:
                pass

        # Remove any node that has been swallowed by the scrolling southern boundary
        self.remembered_nodes = {
            (c, r) for (c, r) in self.remembered_nodes
            if r >= obs.southBound
        }

        # Remove nodes that already have mines on them (regardless of owner)
        for key in obs.mines.keys():
            try:
                col, row = map(int, key.split(","))
                self.remembered_nodes.discard((col, row))
            except ValueError:
                pass

    def get_swallowed_step(self, row, current_step, current_south, scroll_counter, config):
        """Predicts the exact step when the given row will scroll below the southern boundary."""
        scroll_ramp_steps = getattr(config, "scrollRampSteps", 400)
        scroll_start_interval = getattr(config, "scrollStartInterval", 4)
        scroll_end_interval = getattr(config, "scrollEndInterval", 1)

        def get_scroll_interval(s):
            if s >= scroll_ramp_steps:
                return scroll_end_interval
            progress = s / max(1, scroll_ramp_steps)
            interval = scroll_start_interval - (scroll_start_interval - scroll_end_interval) * progress
            return max(scroll_end_interval, round(interval))

        south = current_south
        counter = scroll_counter
        step = current_step

        while step <= 500:
            if south > row:
                return step
            counter -= 1
            if counter <= 0:
                south += 1
                counter = get_scroll_interval(step)
            step += 1
        return 501

    def get_build_choice(self, obs, cartographer, friendly_units, config, should_build_worker=False):
        """
        Evaluates current resources and unit count to determine the optimal build action.
        Returns:
            1 (Scout), 2 (Worker), 3 (Miner), or None
        """
        step = obs.step

        # 1. Step 400 Financial Freeze
        if step >= 400:
            return None

        factory_uid = None
        for uid, unit in friendly_units.items():
            if unit["type"] == 0:
                factory_uid = uid
                break

        if not factory_uid:
            return None

        factory = friendly_units[factory_uid]

        # Spawning cooldown check
        if factory["build_cd"] > 0:
            return None

        # Update our mining node tracking
        self.update_nodes(obs)

        # Count currently active friendly robots
        active_scouts = sum(1 for u in friendly_units.values() if u["type"] == 1)
        active_workers = sum(1 for u in friendly_units.values() if u["type"] == 2)
        active_miners = sum(1 for u in friendly_units.values() if u["type"] == 3)

        scout_cost = getattr(config, "scoutCost", 50)
        worker_cost = getattr(config, "workerCost", 200)
        miner_cost = getattr(config, "minerCost", 300)

        # Helper: check if factory has enough energy (with a 100 energy safety margin)
        def can_afford(cost):
            return factory["energy"] > cost + 100

        # --- A. Scout Cap Utility ---
        scout_utility = 0.0
        if step < 150 and can_afford(scout_cost):
            if active_scouts < 1:
                scout_utility = 1.0
            elif active_scouts == 1:
                scout_utility = 0.2
            else:
                scout_utility = 0.0

        # --- B. Worker Emergency/Offensive Utility ---
        worker_utility = 0.0
        if can_afford(worker_cost):
            if should_build_worker and active_workers == 0:
                worker_utility = 0.95
            else:
                if active_workers == 0:
                    # Run pathfinding to see if Factory has any path to move northward
                    scroll_counter = getattr(obs, "scrollCounter", 4)
                    paths = find_reachable_paths(
                        cartographer, (factory["col"], factory["row"]),
                        step, obs.southBound, scroll_counter,
                        getattr(config, "factoryMovePeriod", 2), config, max_depth=10,
                        initial_jump_cd=factory["jump_cd"]
                    )
                    # If no reachable cell has a row strictly higher than current row, we are blocked
                    has_forward_path = any(pos[1] > factory["row"] for pos in paths.keys())
                    if not has_forward_path:
                        worker_utility = 0.9

        # --- C. Miner ROI Utility ---
        miner_utility = 0.0
        if can_afford(miner_cost):
            if active_miners == 0:
                miner_utility = 0.7
            scroll_counter = getattr(obs, "scrollCounter", 4)
            factory_pos = (factory["col"], factory["row"])

            # Check all known nodes and evaluate if any are viable and untargeted
            for node in self.remembered_nodes:
                # Only target nodes on our side of the mirror axis
                our_side = (node[0] < config.width // 2) if obs.player == 0 else (node[0] >= config.width // 2)
                if not our_side:
                    continue
                # Only target nodes strictly north of the Factory plus a buffer of 3
                if node[1] < factory_pos[1] + 3:
                    continue
                # 1. Skip if already mined
                if f"{node[0]},{node[1]}" in obs.mines:
                    continue

                # 2. Skip if an existing miner is already at this node
                miner_already_there = any(
                    (u["col"], u["row"]) == node and u["type"] == 3
                    for u in friendly_units.values()
                )
                if miner_already_there:
                    continue

                # 3. Calculate path distance for a Miner (move period = 2)
                path = find_path(
                    cartographer, factory_pos, node,
                    step, obs.southBound, scroll_counter,
                    2, config
                )
                if path is None:
                    continue
                # Reject paths that go too far south of the Factory
                min_row = min(pos[1] for pos in path)
                if min_row < factory_pos[1] - 1:
                    continue

                path_len = len(path)
                arrival_turns = 2 * path_len + 1  # 2 turns per step + 1 turn to transform

                factory_move_period = getattr(config, "factoryMovePeriod", 2)
                expected_factory_row = factory_pos[1] + (arrival_turns // factory_move_period)
                if node[1] < expected_factory_row:
                    continue

                t_swallowed = self.get_swallowed_step(
                    node[1], step, obs.southBound, scroll_counter, config
                )
                surviving_turns = t_swallowed - step

                # ROI condition: Surviving Turns - Arrival Turns > 8
                if surviving_turns - arrival_turns > 8:
                    miner_utility = 0.8
                    break

        # Select the choice with the highest utility
        utilities = {
            1: scout_utility,
            2: worker_utility,
            3: miner_utility
        }

        best_type = max(utilities, key=utilities.get)
        if utilities[best_type] > 0.0:
            return best_type
        return None

    def get_liquidation_targets(self, obs, cartographer, friendly_units, config):
        """
        Post-step 400 Capital Liquidation: identify friendly mines with accumulated
        energy so the Factory can route over them and vacuum the capital for the
        end-game tiebreaker score.
        Returns:
            list of (col, row, energy) sorted by energy descending.
        """
        targets = []
        for key, mine_data in obs.mines.items():
            try:
                col, row = map(int, key.split(","))
            except ValueError:
                continue

            mine_energy = mine_data[0]
            mine_owner = mine_data[2]

            # Only harvest our own mines that have energy
            if mine_owner == obs.player and mine_energy > 0:
                # Skip mines that are about to be swallowed
                if row <= obs.southBound + 2:
                    continue
                targets.append((col, row, mine_energy))

        # Sort by energy descending — harvest the richest mines first
        targets.sort(key=lambda t: -t[2])
        return targets
# === End of economy.py ===

# === Start of tactician.py ===
try:
    _ = TACTICS_PARAMS
except NameError:
    TACTICS_PARAMS = {
        "WORKER_THRESHOLD": 2,
        "SAFETY_BUFFER": 2
    }


class EnemyTracker:
    def __init__(self):
        self.col_min = None
        self.col_max = None
        self.row_min = None
        self.row_max = None
        self.last_seen_step = -1
        self.jump_cd = 0
        self.last_exact_pos = None

    def update(self, obs, config):
        # Decrement jump cooldown
        self.jump_cd = max(0, self.jump_cd - 1)

        # 1. Search for actual visible enemy factory
        found = False
        for uid, data in obs.robots.items():
            rtype, col, row, energy, owner = data[0], data[1], data[2], data[3], data[4]
            if owner != obs.player and rtype == 0:  # Enemy Factory
                # Check if position changed by 2 cells in one step -> Jump detected
                if self.last_exact_pos:
                    dist = abs(col - self.last_exact_pos[0]) + abs(row - self.last_exact_pos[1])
                    if dist == 2 or abs(col - self.last_exact_pos[0]) == 2 or abs(row - self.last_exact_pos[1]) == 2:
                        self.jump_cd = 20

                self.col_min = col
                self.col_max = col
                self.row_min = row
                self.row_max = row
                self.last_seen_step = obs.step
                self.last_exact_pos = (col, row)

                # Sync directly with visible jump_cd if available
                if len(data) > 6:
                    self.jump_cd = data[6]

                found = True
                break

        # 2. Bounding box expansion if hidden under fog
        if not found:
            if self.col_min is None:
                # Initialize using horizontal mirror of our Factory
                our_col, our_row = 5, 2
                for uid, data in obs.robots.items():
                    if data[4] == obs.player and data[0] == 0:
                        our_col, our_row = data[1], data[2]
                        break
                self.col_min = config.width - 1 - our_col
                self.col_max = config.width - 1 - our_col
                self.row_min = our_row
                self.row_max = our_row
                self.last_exact_pos = (self.col_min, self.row_min)
                self.last_seen_step = obs.step
            else:
                # Expand bounding box by 1 row/col every 2 turns
                turns_since_seen = obs.step - self.last_seen_step
                if turns_since_seen > 0 and turns_since_seen % 2 == 0:
                    self.col_min = max(0, self.col_min - 1)
                    self.col_max = min(config.width - 1, self.col_max + 1)
                    self.row_min = max(obs.southBound + 1, self.row_min + (1 if obs.step > 250 else 0))
                    self.row_max = min(obs.northBound, self.row_max + 1)

def find_doorways(cartographer):
    door_rows = []
    w = cartographer.width
    c1 = w // 2 - 1
    c2 = w // 2
    # Scan rows from south_bound to north_bound
    for r in range(cartographer.south_bound, cartographer.north_bound + 1):
        if (c1, r) in cartographer.global_map or (c2, r) in cartographer.global_map:
            if not cartographer.is_wall(c1, r, "EAST"):
                door_rows.append(r)
    return door_rows

class TacticalController:
    def __init__(self):
        self.built_walls = set()  # Track walls we've built: (col, row, direction)

    def assign_tactical_goals(self, obs, cartographer, friendly_units, enemy_tracker, config):
        door_rows = find_doorways(cartographer)
        w = cartographer.width
        c1 = w // 2 - 1
        c2 = w // 2
        our_side_col = c1 if obs.player == 0 else c2
        enemy_side_col = c2 if obs.player == 0 else c1

        # --- Counter-Wall Re-Trapping: detect cleared walls and queue re-builds ---
        retrap_overrides = {}  # uid -> build_action_string
        cleared_walls = set()
        for (wc, wr, wdir) in list(self.built_walls):
            # Remove walls that have scrolled below the boundary
            if wr < obs.southBound:
                self.built_walls.discard((wc, wr, wdir))
                continue
            # Check if the wall still exists
            if not cartographer.is_wall(wc, wr, wdir):
                cleared_walls.add((wc, wr, wdir))

        # For each cleared wall, find an adjacent alive Worker to re-build it
        if cleared_walls:
            workers_list = [(uid, u) for uid, u in friendly_units.items() if u["type"] == 2]
            for (wc, wr, wdir) in cleared_walls:
                for w_uid, w_unit in workers_list:
                    if w_uid in retrap_overrides:
                        continue
                    if w_unit["col"] == wc and w_unit["row"] == wr:
                        # Worker is on the exact cell — rebuild
                        if w_unit["energy"] >= 100:
                            retrap_overrides[w_uid] = f"BUILD_{wdir}"
                            break

        # Group friendly robots by type
        scouts = []
        workers = []
        miners = []
        for uid, unit in friendly_units.items():
            if unit["type"] == 1:
                scouts.append((uid, unit))
            elif unit["type"] == 2:
                workers.append((uid, unit))
            elif unit["type"] == 3:
                miners.append((uid, unit))

        # Sort to ensure consistent behavior
        scouts.sort(key=lambda x: x[0])
        workers.sort(key=lambda x: x[0])
        miners.sort(key=lambda x: x[0])

        tactical_targets = {}  # uid -> target_cell
        worker_trap_actions = {}  # uid -> build_action_string
        should_build_worker = False

        # Enemy Factory projected center position
        ef_col = (enemy_tracker.col_min + enemy_tracker.col_max) // 2
        ef_row = enemy_tracker.row_max  # Target row_max for safety containment

        # --- Counter-Wall Re-Trapping: detect cleared walls and queue re-builds ---
        retrap_overrides = {}  # uid -> build_action_string
        cleared_walls = set()
        for (wc, wr, wdir) in list(self.built_walls):
            # Remove walls that have scrolled below the boundary
            if wr < obs.southBound:
                self.built_walls.discard((wc, wr, wdir))
                continue
            # Check if the wall still exists
            if not cartographer.is_wall(wc, wr, wdir):
                cleared_walls.add((wc, wr, wdir))

        # For each cleared wall, find an adjacent alive Worker to re-build it
        if cleared_walls:
            for (wc, wr, wdir) in cleared_walls:
                for w_uid, w_unit in workers:
                    if w_uid in retrap_overrides:
                        continue
                    if w_unit["col"] == wc and w_unit["row"] == wr:
                        if w_unit["energy"] >= 100:
                            retrap_overrides[w_uid] = f"BUILD_{wdir}"
                            break

        # --- Adversarial Doorway Welding + Double-Lock airlift ---
        tracking_center_row = (enemy_tracker.row_min + enemy_tracker.row_max) // 2
        active_door_rows = [r for r in door_rows if r >= obs.southBound]
        target_door_row = None
        min_door_dist = float('inf')
        for r in active_door_rows:
            dist = abs(tracking_center_row - r)
            if dist <= 3 and dist < min_door_dist:
                min_door_dist = dist
                target_door_row = r

        best_sec_uid = None
        double_lock_col = None
        is_primary_built = False
        build_dir = "EAST" if obs.player == 0 else "WEST"

        if target_door_row is not None:
            double_lock_col = our_side_col - 1 if obs.player == 0 else our_side_col + 1
            is_primary_built = cartographer.is_wall(our_side_col, target_door_row, build_dir)

            # Find primary worker
            primary_worker_uid = None
            best_p_dist = float('inf')
            for w_uid, w_unit in workers:
                dist = abs(w_unit["col"] - our_side_col) + abs(w_unit["row"] - target_door_row)
                if dist < best_p_dist:
                    best_p_dist = dist
                    primary_worker_uid = w_uid

            if is_primary_built:
                # Find best secondary unit (Scout or other Worker)
                best_sec_dist = float('inf')
                candidates = []
                for s_uid, s_unit in scouts:
                    candidates.append((s_uid, s_unit))
                for w_uid, w_unit in workers:
                    if w_uid != primary_worker_uid:
                        candidates.append((w_uid, w_unit))

                for c_uid, c_unit in candidates:
                    dist = abs(c_unit["col"] - double_lock_col) + abs(c_unit["row"] - target_door_row)
                    if dist < best_sec_dist:
                        best_sec_dist = dist
                        best_sec_uid = c_uid

                if best_sec_uid:
                    tactical_targets[best_sec_uid] = (double_lock_col, target_door_row)

        # 1. Scout Resource Starvation & Interception
        scroll_counter = getattr(obs, "scrollCounter", 4)
        enemy_paths = {}
        if ef_col is not None and ef_row is not None:
            enemy_paths = find_reachable_paths(
                cartographer, (ef_col, ef_row),
                obs.step, obs.southBound, scroll_counter,
                getattr(config, "factoryMovePeriod", 2), config,
                max_depth=10, initial_jump_cd=enemy_tracker.jump_cd
            )

        assigned_targets = set()
        if target_door_row is not None:
            assigned_targets.add((our_side_col, target_door_row))
            assigned_targets.add((double_lock_col, target_door_row))

        for i, (s_uid, s_unit) in enumerate(scouts):
            if i <= 1:
                if s_uid in tactical_targets:
                    assigned_targets.add(tactical_targets[s_uid])
                    continue  # assigned to double lock

                # Snatch crystals from enemy Factory's path
                intercept_target = None
                best_crystal_priority = -1

                for key, val in obs.crystals.items():
                    try:
                        cc, cr = map(int, key.split(","))
                        if (cc, cr) in enemy_paths:
                            enemy_path_len = len(enemy_paths[(cc, cr)])
                            enemy_arrival_turns = getattr(config, "factoryMovePeriod", 2) * enemy_path_len

                            p = find_path(
                                cartographer, (s_unit["col"], s_unit["row"]), (cc, cr),
                                obs.step, obs.southBound, scroll_counter,
                                1, config
                            )
                            if p is not None:
                                scout_arrival_turns = len(p)
                                if scout_arrival_turns <= enemy_arrival_turns - 1:
                                    if (cc, cr) not in assigned_targets:
                                        priority = val - scout_arrival_turns
                                        if priority > best_crystal_priority:
                                            best_crystal_priority = priority
                                            intercept_target = (cc, cr)
                    except Exception:
                        pass

                if intercept_target:
                    tactical_targets[s_uid] = intercept_target
                    assigned_targets.add(intercept_target)
                else:
                    # Fallback to standard starvation vacuuming
                    starve_crystals = []
                    for key in obs.crystals.keys():
                        try:
                            cc, cr = map(int, key.split(","))
                            dist_to_path = abs(cc - ef_col)
                            if dist_to_path <= 5 and cr >= ef_row - 2 and cr <= ef_row + 10:
                                if (cc, cr) not in assigned_targets:
                                    starve_crystals.append((cc, cr))
                        except ValueError:
                            pass

                    if starve_crystals:
                        starve_crystals.sort(key=lambda pos: abs(pos[0] - s_unit["col"]) + abs(pos[1] - s_unit["row"]))
                        tactical_targets[s_uid] = starve_crystals[0]
                        assigned_targets.add(starve_crystals[0])
                    elif door_rows and (ef_col, enemy_tracker.row_max) not in assigned_targets:
                        tactical_targets[s_uid] = (ef_col, enemy_tracker.row_max)
                        assigned_targets.add((ef_col, enemy_tracker.row_max))
                    else:
                        row_candidate = max(obs.southBound, min(s_unit["row"], obs.northBound))
                        while (our_side_col, row_candidate) in assigned_targets and row_candidate > obs.southBound:
                            row_candidate -= 1
                        tactical_targets[s_uid] = (our_side_col, row_candidate)
                        assigned_targets.add((our_side_col, row_candidate))

        # 2. Worker Wall Trap Containment (with counter-wall re-trapping)
        for w_uid, w_unit in workers:
            # Check if this worker is the secondary double-lock worker
            if w_uid == best_sec_uid:
                if w_unit["col"] == double_lock_col and w_unit["row"] == target_door_row:
                    if is_primary_built and not cartographer.is_wall(double_lock_col, target_door_row, build_dir):
                        if w_unit["energy"] >= 100:
                            worker_trap_actions[w_uid] = f"BUILD_{build_dir}"
                            self.built_walls.add((double_lock_col, target_door_row, build_dir))
                tactical_targets[w_uid] = (double_lock_col, target_door_row)
                continue

            # Counter-wall re-trap override takes highest priority
            if w_uid in retrap_overrides:
                worker_trap_actions[w_uid] = retrap_overrides[w_uid]
                tactical_targets[w_uid] = (w_unit["col"], w_unit["row"])
                continue

            w_col, w_row = w_unit["col"], w_unit["row"]

            # --- Adversarial Doorway Welding ---
            if target_door_row is not None:
                # Throat of the doorway tile on our side
                target_cell = (our_side_col, target_door_row)
                if w_col == our_side_col and w_row == target_door_row:
                    if not cartographer.is_wall(w_col, w_row, build_dir):
                        if w_unit["energy"] >= 100:
                            worker_trap_actions[w_uid] = f"BUILD_{build_dir}"
                            self.built_walls.add((w_col, w_row, build_dir))
                        tactical_targets[w_uid] = (w_col, w_row)
                else:
                    tactical_targets[w_uid] = target_cell
                continue

            # --- Standard Containment Trapping ---
            target_cell = (ef_col, ef_row + 1)

            # Check if adjacent to the enemy Factory's cell and block it
            if w_row == ef_row + 1 and w_col == ef_col:
                if not cartographer.is_wall(w_col, w_row, "SOUTH"):
                    worker_trap_actions[w_uid] = "BUILD_SOUTH"
                    tactical_targets[w_uid] = (w_col, w_row)
                    self.built_walls.add((w_col, w_row, "SOUTH"))
            elif w_row == ef_row and w_col == ef_col - 1:
                if not cartographer.is_wall(w_col, w_row, "EAST"):
                    worker_trap_actions[w_uid] = "BUILD_EAST"
                    tactical_targets[w_uid] = (w_col, w_row)
                    self.built_walls.add((w_col, w_row, "EAST"))
            elif w_row == ef_row and w_col == ef_col + 1:
                if not cartographer.is_wall(w_col, w_row, "WEST"):
                    worker_trap_actions[w_uid] = "BUILD_WEST"
                    tactical_targets[w_uid] = (w_col, w_row)
                    self.built_walls.add((w_col, w_row, "WEST"))
            else:
                # Path to trap position
                tactical_targets[w_uid] = target_cell

        # 3. Symmetrical Door Camping
        enemy_units = []
        for uid, data in obs.robots.items():
            rtype, col, row, energy, owner = data[0], data[1], data[2], data[3], data[4]
            if owner != obs.player:
                enemy_units.append((col, row, rtype))

        used_guardians = set()
        for d_row in door_rows:
            our_door_cell = (our_side_col, d_row)
            enemy_door_cell = (enemy_side_col, d_row)

            # Check if any enemy unit is close to the door on their side (distance <= 2)
            enemy_near = False
            for ec, er, etype in enemy_units:
                if abs(ec - enemy_door_cell[0]) + abs(er - enemy_door_cell[1]) <= 2:
                    enemy_near = True
                    break

            if enemy_near:
                best_guardian = None
                best_dist = float('inf')
                potential_guardians = workers

                for g_uid, g_unit in potential_guardians:
                    if g_uid in used_guardians or g_uid in tactical_targets:
                        continue
                    dist = abs(g_unit["col"] - our_door_cell[0]) + abs(g_unit["row"] - our_door_cell[1])
                    if dist < best_dist and dist < 10:
                        best_dist = dist
                        best_guardian = g_uid

                if best_guardian:
                    tactical_targets[best_guardian] = our_door_cell
                    used_guardians.add(best_guardian)

        # 4. Offensive Worker Spawning Authorization:
        # High confidence = bounding box width and height <= WORKER_THRESHOLD, and doors are mapped, and we have 0 workers
        is_high_confidence = (
            (enemy_tracker.col_max - enemy_tracker.col_min) <= TACTICS_PARAMS["WORKER_THRESHOLD"] and
            (enemy_tracker.row_max - enemy_tracker.row_min) <= TACTICS_PARAMS["WORKER_THRESHOLD"]
        )
        if len(door_rows) > 0 and is_high_confidence and len(workers) == 0:
            should_build_worker = True

        return tactical_targets, worker_trap_actions, should_build_worker
# === End of tactician.py ===

# === Start of orchestrator.py ===
try:
    _ = TACTICS_PARAMS
except NameError:
    TACTICS_PARAMS = {
        "WORKER_THRESHOLD": 2,
        "SAFETY_BUFFER": 2
    }

import time

class TrafficController:
    def __init__(self, enable_tactics=True):
        self.unit_paths = {}  # uid -> list of (col, row)
        self.unit_targets = {}  # uid -> (col, row)
        self.macro_manager = MacroManager()
        self.enable_tactics = enable_tactics
        self.enemy_tracker = EnemyTracker()
        self.tactical_controller = TacticalController()
        self.last_turn_elapsed = None
        self.max_depth = 15
        self.factory_reservations = set()

    def _is_fixed_wall(self, cartographer, col, row, direction):
        width = cartographer.width
        if direction == "WEST" and col == 0:
            return True
        if direction == "EAST" and col == width - 1:
            return True
        if direction == "EAST" and col == width // 2 - 1:
            return True
        if direction == "WEST" and col == width // 2:
            return True
        return False

    def _action_destination(self, col, row, action):
        if not action:
            return (col, row)
        if action in ("NORTH", "SOUTH", "EAST", "WEST"):
            dc, dr = {
                "NORTH": (0, 1),
                "SOUTH": (0, -1),
                "EAST": (1, 0),
                "WEST": (-1, 0)
            }[action]
            return (col + dc, row + dr)
        if action.startswith("JUMP_"):
            direction = action.split("_", 1)[1]
            dc, dr = {
                "NORTH": (0, 1),
                "SOUTH": (0, -1),
                "EAST": (1, 0),
                "WEST": (-1, 0)
            }[direction]
            return (col + dc * 2, row + dr * 2)
        return (col, row)

    def _broadcast_factory_reservations(self, factory_uid, friendly_units, actions, horizon=5):
        self.factory_reservations = set()
        if not factory_uid or factory_uid not in friendly_units:
            return

        factory = friendly_units[factory_uid]
        col, row = factory["col"], factory["row"]
        self.factory_reservations.add((col, row, 0))

        trajectory = []
        action_dest = self._action_destination(col, row, actions.get(factory_uid))
        if action_dest != (col, row):
            trajectory.append(action_dest)

        for pos in self.unit_paths.get(factory_uid) or []:
            if len(trajectory) >= horizon:
                break
            trajectory.append(pos)

        for offset, (r_col, r_row) in enumerate(trajectory[:horizon], start=1):
            self.factory_reservations.add((r_col, r_row, offset))

    def _path_clearing_action(self, uid, unit, cartographer, obs, config, reserved_cells, enemy_positions, scroll_counter, move_period):
        if unit["type"] not in (1, 2) or not self.factory_reservations:
            return None

        col, row = unit["col"], unit["row"]
        reserved_track = {(c, r) for c, r, _ in self.factory_reservations}
        planned_path = self.unit_paths.get(uid) or []
        planned_next = planned_path[0] if planned_path else None
        if (col, row) not in reserved_track and planned_next not in reserved_track:
            return None

        projected_south = project_south_bound(
            obs.step, obs.southBound, scroll_counter, move_period, config
        )

        candidates = []
        for direction in ["EAST", "WEST", "NORTH", "SOUTH"]:
            if not cartographer.is_walkable(col, row, direction):
                continue
            dc, dr = cartographer.DIR_OFFSETS[direction]
            nc, nr = col + dc, row + dr
            n_pos = (nc, nr)
            if n_pos in reserved_track:
                continue
            if n_pos in reserved_cells and reserved_cells[n_pos] != uid:
                continue
            if n_pos in enemy_positions:
                continue
            if nr < projected_south or nr > cartographer.north_bound:
                continue

            if reserved_track:
                distance = min(abs(nc - rc) + abs(nr - rr) for rc, rr in reserved_track)
            else:
                distance = 0
            side_bonus = 100 if direction in ("EAST", "WEST") else 0
            score = side_bonus + distance * 10 + nr
            candidates.append((score, direction, n_pos))

        if candidates:
            candidates.sort(reverse=True)
            _, direction, n_pos = candidates[0]
            return direction, n_pos

        if unit["type"] == 2 and unit["energy"] >= 100:
            for direction in ["EAST", "WEST"]:
                if cartographer.is_wall(col, row, direction) and not self._is_fixed_wall(cartographer, col, row, direction):
                    return f"REMOVE_{direction}", (col, row)

        return "IDLE", (col, row)

    def find_blocking_wall(self, cartographer, factory_pos, obs, config):
        """
        BFS ignoring standard walls but respecting fixed walls to find the first
        standard wall blocking the Factory from moving northward.
        """
        width = cartographer.width

        def is_fixed_wall(c, r, direction):
            if direction == "WEST" and c == 0:
                return True
            if direction == "EAST" and c == width - 1:
                return True
            if direction == "EAST" and c == width // 2 - 1:
                return True
            if direction == "WEST" and c == width // 2:
                return True
            return False

        from collections import deque
        queue = deque([(factory_pos[0], factory_pos[1], [])])
        visited = {factory_pos}
        target_row = factory_pos[1] + 2

        scroll_counter = getattr(obs, "scrollCounter", 4)

        while queue:
            c, r, path = queue.popleft()
            if r >= target_row:
                # Trace back to find the first transition blocked by a standard wall
                for vc, vr, d, nc, nr in path:
                    if cartographer.is_wall(vc, vr, d):
                        if not is_fixed_wall(vc, vr, d):
                            return (vc, vr), d
                return None

            for direction, offset in cartographer.DIR_OFFSETS.items():
                nc, nr = c + offset[0], r + offset[1]
                if nc < 0 or nc >= width or nr < 0:
                    continue
                if is_fixed_wall(c, r, direction):
                    continue



                if (nc, nr) not in visited:
                    visited.add((nc, nr))
                    queue.append((nc, nr, path + [(c, r, direction, nc, nr)]))

        return None

    def process_turn(self, obs, cartographer, config):
        """
        Coordinates movement intents for all friendly units to avoid collisions.
        Returns:
            dict of actions mapping uid -> action_string.
        """
        start_time = time.time()

        if self.last_turn_elapsed is not None and self.last_turn_elapsed < 0.1:
            self.max_depth = 25
        else:
            self.max_depth = 15

        player = obs.player
        scroll_counter = getattr(obs, "scrollCounter", 4)
        actions = {}
        dynamic_safety_buffer = max(2, min(5, 2 + (obs.step // 120)))
        is_seeking_mine = False
        is_chasing_enemy = False

        # 1. Update macro manager with global observations
        self.macro_manager.update(obs)

        # 2. Identify all friendly units and their state
        friendly_units = {}
        for uid, data in obs.robots.items():
            rtype, col, row, energy, owner = data[0], data[1], data[2], data[3], data[4]
            if owner == player:
                friendly_units[uid] = {
                    "type": rtype,
                    "col": col,
                    "row": row,
                    "energy": energy,
                    "move_cd": data[5],
                    "jump_cd": data[6],
                    "build_cd": data[7] if len(data) > 7 else 0
                }

        # 2_enemy. Identify all enemy unit positions as blocked cells
        enemy_positions = set()
        enemy_factory_energy = 0
        for uid, data in obs.robots.items():
            rtype, col, row, energy, owner = data[0], data[1], data[2], data[3], data[4]
            if owner != player:
                enemy_positions.add((col, row))
                if rtype == 0:
                    enemy_factory_energy = energy

        # 2b. Update tactics tracking and get target overrides
        self.enemy_tracker.update(obs, config)
        tactical_targets = {}
        worker_trap_actions = {}
        should_build_worker = False
        if self.enable_tactics:
            tactical_targets, worker_trap_actions, should_build_worker = self.tactical_controller.assign_tactical_goals(
                obs, cartographer, friendly_units, self.enemy_tracker, config
            )

        # 2c. Death-Row Salvage: doomed Scouts/Workers near south boundary dump energy to Factory
        factory_pos_for_salvage = None
        for uid, unit in friendly_units.items():
            if unit["type"] == 0:
                factory_pos_for_salvage = (unit["col"], unit["row"])
                break

        if factory_pos_for_salvage:
            projected_south_3 = project_south_bound(
                obs.step, obs.southBound, scroll_counter, 3, config
            )
            for uid, unit in friendly_units.items():
                if unit["type"] not in (1, 2):  # Only Scouts and Workers
                    continue
                if uid in tactical_targets:
                    continue  # Don't override existing tactical assignment
                u_row = unit["row"]
                u_col = unit["col"]
                # Check if the unit will be swallowed within 3 turns
                if u_row < projected_south_3:
                    # Check if adjacent to Factory (Manhattan distance 1, no wall)
                    dx = factory_pos_for_salvage[0] - u_col
                    dy = factory_pos_for_salvage[1] - u_row
                    manhattan = abs(dx) + abs(dy)
                    if manhattan == 1:
                        # Determine transfer direction
                        transfer_dir = None
                        if (dx, dy) == (0, 1):
                            transfer_dir = "NORTH"
                        elif (dx, dy) == (0, -1):
                            transfer_dir = "SOUTH"
                        elif (dx, dy) == (1, 0):
                            transfer_dir = "EAST"
                        elif (dx, dy) == (-1, 0):
                            transfer_dir = "WEST"
                        if transfer_dir and not cartographer.is_wall(u_col, u_row, transfer_dir):
                            # Override: force TRANSFER to dump energy into Factory
                            tactical_targets[uid] = (u_col, u_row)  # Stay in place
                            worker_trap_actions[uid] = f"TRANSFER_{transfer_dir}"
                            continue
                    # Not adjacent — route toward Factory
                    tactical_targets[uid] = factory_pos_for_salvage

        # 3. Initialize space-time booking registry with all current friendly positions
        # This prevents other units from moving onto occupied cells unless the occupant vacates.
        reserved_cells = {}  # (col, row) -> uid
        for uid, unit in friendly_units.items():
            reserved_cells[(unit["col"], unit["row"])] = uid

        # 4. Identify active vs stationary units
        stationary_uids = []
        active_uids = []
        for uid, unit in friendly_units.items():
            if unit["energy"] == 0 or unit["move_cd"] > 0:
                stationary_uids.append(uid)
            else:
                active_uids.append(uid)

        # 5. Check Factory spawn intent using CFO
        factory_uid = None
        for uid, unit in friendly_units.items():
            if unit["type"] == 0:  # Factory
                factory_uid = uid
                break

        factory_spawn_cell = None
        factory_build_action = None
        if factory_uid and factory_uid in active_uids:
            f_unit = friendly_units[factory_uid]
            build_choice = self.macro_manager.get_build_choice(obs, cartographer, friendly_units, config, should_build_worker)
            if build_choice is not None:
                type_name = {1: "SCOUT", 2: "WORKER", 3: "MINER"}[build_choice]
                # Find the first walkable spawn direction not already reserved
                for d in ["NORTH", "EAST", "WEST", "SOUTH"]:
                    if cartographer.is_walkable(f_unit["col"], f_unit["row"], d):
                        dc, dr = cartographer.DIR_OFFSETS[d]
                        sc, sr = f_unit["col"] + dc, f_unit["row"] + dr
                        if (sc, sr) not in reserved_cells:
                            # Reserve the spawn cell
                            reserved_cells[(sc, sr)] = f"SPAWN_{factory_uid}"
                            factory_build_action = f"BUILD_{type_name}_{d}"
                            factory_spawn_cell = (sc, sr)
                            break

        # 5b. Late-Game Capital Liquidation / Low-Energy Mine Harvesting: Route Factory over friendly mines
        factory_liquidation_target = None
        if factory_uid and factory_uid in active_uids and not factory_build_action:
            if obs.step >= 400 or friendly_units[factory_uid]["energy"] < 600:
                liquidation_targets = self.macro_manager.get_liquidation_targets(
                    obs, cartographer, friendly_units, config
                )
                if liquidation_targets:
                    f_unit = friendly_units[factory_uid]
                    f_pos = (f_unit["col"], f_unit["row"])
                    # Find the nearest reachable liquidation target
                    best_liq = None
                    best_liq_dist = float('inf')
                    for lc, lr, lenergy in liquidation_targets:
                        p = find_path(
                            cartographer, f_pos, (lc, lr),
                            obs.step, obs.southBound, scroll_counter,
                            getattr(config, "factoryMovePeriod", 2), config,
                            initial_jump_cd=f_unit["jump_cd"],
                            blocked_cells=enemy_positions
                        )
                        if p is not None and len(p) < best_liq_dist:
                            best_liq_dist = len(p)
                            best_liq = (lc, lr)
                    if best_liq:
                        factory_liquidation_target = best_liq
                        tactical_targets[factory_uid] = factory_liquidation_target
                        is_seeking_mine = True

        # 5c. Factory Chase Mode: Target the enemy factory for assassination
        if factory_uid and factory_uid in active_uids and factory_uid not in tactical_targets:
            f_unit = friendly_units[factory_uid]
            f_pos = (f_unit["col"], f_unit["row"])
            # Use enemy tracker to get the best estimate of enemy factory position
            ef_col = (self.enemy_tracker.col_min + self.enemy_tracker.col_max) // 2
            ef_row = (self.enemy_tracker.row_min + self.enemy_tracker.row_max) // 2
            if ef_col is not None and ef_row is not None:
                chase_target = (ef_col, ef_row)
                p = find_path(
                    cartographer, f_pos, chase_target,
                    obs.step, obs.southBound, scroll_counter,
                    getattr(config, "factoryMovePeriod", 2), config,
                    initial_jump_cd=f_unit["jump_cd"],
                    safety_buffer=0,
                    blocked_cells=enemy_positions
                )
                if p is not None:
                    tactical_targets[factory_uid] = chase_target
                    is_chasing_enemy = True
                else:
                    # Can't path directly - try to get to the nearest doorway on enemy side
                    # to cross over
                    door_rows = []
                    c1 = cartographer.width // 2 - 1
                    c2 = cartographer.width // 2
                    enemy_side_col = c2 if obs.player == 0 else c1
                    for r in range(obs.southBound, obs.northBound + 1):
                        if (c1, r) in cartographer.global_map or (c2, r) in cartographer.global_map:
                            if not cartographer.is_wall(c1, r, "EAST"):
                                door_rows.append(r)

                    if door_rows:
                        # Find the doorway closest to the enemy factory row
                        best_door = min(door_rows, key=lambda dr: abs(dr - ef_row))
                        # Target the enemy side of the doorway
                        door_target = (enemy_side_col, best_door)
                        p2 = find_path(
                            cartographer, f_pos, door_target,
                            obs.step, obs.southBound, scroll_counter,
                            getattr(config, "factoryMovePeriod", 2), config,
                            initial_jump_cd=f_unit["jump_cd"],
                            safety_buffer=0,
                            blocked_cells=enemy_positions
                        )
                        if p2 is not None:
                            tactical_targets[factory_uid] = door_target
                            is_chasing_enemy = True
                        else:
                            # Try our side of the doorway as intermediate target
                            our_side_col = c1 if obs.player == 0 else c2
                            our_door_target = (our_side_col, best_door)
                            p3 = find_path(
                                cartographer, f_pos, our_door_target,
                                obs.step, obs.southBound, scroll_counter,
                                getattr(config, "factoryMovePeriod", 2), config,
                                initial_jump_cd=f_unit["jump_cd"],
                                safety_buffer=0,
                                blocked_cells=enemy_positions
                            )
                            if p3 is not None:
                                tactical_targets[factory_uid] = our_door_target
                                is_chasing_enemy = True

        # 6. Define priority sorting function for active units
        # Priority: Factory (0) > Workers (2) / Miners (3) > Scouts (1)
        def get_priority(uid):
            rtype = friendly_units[uid]["type"]
            if uid == factory_uid:
                return 0  # Factory must publish its path before escorts act
            elif rtype == 0:
                return 1
            elif rtype in [2, 3]:
                return 2  # Medium priority
            else:
                return 3  # Lowest priority

        # Sort active uids by priority
        active_uids.sort(key=get_priority)
        factory_reservations_broadcast = False
        self.factory_reservations = set()
        if factory_uid and factory_uid not in active_uids:
            self._broadcast_factory_reservations(factory_uid, friendly_units, actions)
            factory_reservations_broadcast = True

        # 7. Resolve active units in priority order
        for uid in active_uids:
            if uid != factory_uid and not factory_reservations_broadcast:
                self._broadcast_factory_reservations(factory_uid, friendly_units, actions)
                factory_reservations_broadcast = True

            if uid in tactical_targets:
                if self.unit_targets.get(uid) != tactical_targets[uid]:
                    self.unit_paths[uid] = None
                    self.unit_targets[uid] = tactical_targets[uid]
            unit = friendly_units[uid]
            rtype = unit["type"]
            col = unit["col"]
            row = unit["row"]
            jump_cd = unit["jump_cd"]

            # Determine movement period
            if rtype == 0:
                move_period = getattr(config, "factoryMovePeriod", 2)
            elif rtype == 1:
                move_period = 1
            elif rtype == 2:
                move_period = getattr(config, "workerMovePeriod", 2)
            elif rtype == 3:
                move_period = getattr(config, "minerMovePeriod", 2)
            else:
                move_period = 1

            # If this is the Factory and it's spawning, apply the spawn action
            if uid == factory_uid and factory_build_action:
                actions[uid] = factory_build_action
                # Factory stays stationary during spawn, its current cell is already reserved
                continue

            clearing = self._path_clearing_action(
                uid, unit, cartographer, obs, config, reserved_cells, enemy_positions, scroll_counter, move_period
            )
            if clearing:
                clearing_action, clearing_pos = clearing
                actions[uid] = clearing_action
                self.unit_paths[uid] = None
                if clearing_pos != (col, row):
                    if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                        del reserved_cells[(col, row)]
                    reserved_cells[clearing_pos] = uid
                else:
                    reserved_cells[(col, row)] = uid
                continue

            # Death-Row Salvage: any unit flagged for TRANSFER dumps energy immediately
            if uid in worker_trap_actions:
                salvage_action = worker_trap_actions[uid]
                if salvage_action.startswith("TRANSFER_"):
                    actions[uid] = salvage_action
                    continue

            # --- Specialized Miner Behavior ---
            if rtype == 3:
                # 1. Standing on mining node -> TRANSFORM (only if not guarding)
                if uid not in tactical_targets:
                    is_node = (col, row) in self.macro_manager.remembered_nodes or f"{col},{row}" in obs.miningNodes
                    if is_node and f"{col},{row}" not in obs.mines:
                        if obs.step < 400 and unit["energy"] >= 100:
                            actions[uid] = "TRANSFORM"
                            # Miner stays stationary, current cell is already reserved
                            continue

                # 2. Pathfind to target
                best_path = None
                if uid in tactical_targets:
                    t_cell = tactical_targets[uid]
                    if (col, row) == t_cell:
                        actions[uid] = "IDLE"
                        continue
                    best_path = find_path(
                        cartographer, (col, row), t_cell,
                        obs.step, obs.southBound, scroll_counter,
                        move_period, config,
                        blocked_cells=enemy_positions
                    )
                else:
                    closest_node = None
                    min_dist = float('inf')
                    f_pos = None
                    for fu in friendly_units.values():
                        if fu["type"] == 0:
                            f_pos = (fu["col"], fu["row"])
                            break
                    for node in self.macro_manager.remembered_nodes:
                        if f"{node[0]},{node[1]}" in obs.mines:
                            continue
                        # Only target nodes on our side of the mirror axis
                        our_side = (node[0] < cartographer.width // 2) if obs.player == 0 else (node[0] >= cartographer.width // 2)
                        if not our_side:
                            continue
                        if f_pos and node[1] < f_pos[1] + 3:
                            continue
                        p = find_path(
                            cartographer, (col, row), node,
                            obs.step, obs.southBound, scroll_counter,
                            move_period, config,
                            blocked_cells=enemy_positions
                        )
                        if p is not None:
                            path_len = len(p)
                            arrival_turns = move_period * path_len + 1
                            factory_move_period = getattr(config, "factoryMovePeriod", 2)
                            expected_factory_row = f_pos[1] + (arrival_turns // factory_move_period) if f_pos else 0
                            if f_pos and node[1] < expected_factory_row:
                                continue
                            if path_len < min_dist:
                                min_dist = path_len
                                closest_node = node
                                best_path = p

                if best_path:
                    next_pos = best_path[0]
                    dx = next_pos[0] - col
                    dy = next_pos[1] - row
                    direction = None
                    if (dx, dy) == (0, 1):
                        direction = "NORTH"
                    elif (dx, dy) == (0, -1):
                        direction = "SOUTH"
                    elif (dx, dy) == (1, 0):
                        direction = "EAST"
                    elif (dx, dy) == (-1, 0):
                        direction = "WEST"

                    if direction and cartographer.is_walkable(col, row, direction):
                        if next_pos not in reserved_cells:
                            projected_south = project_south_bound(
                                obs.step, obs.southBound, scroll_counter, move_period, config
                            )
                            if next_pos[1] >= projected_south:
                                actions[uid] = direction
                                self.unit_paths[uid] = best_path[1:]
                                # Vacate old cell, reserve new cell
                                if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                                    del reserved_cells[(col, row)]
                                reserved_cells[next_pos] = uid
                                continue

            # --- Specialized Worker Behavior ---
            if rtype == 2:
                if uid in worker_trap_actions:
                    trap_action = worker_trap_actions[uid]
                    if trap_action.startswith("TRANSFER_"):
                        # Death-Row Salvage: dump energy into Factory unconditionally
                        actions[uid] = trap_action
                        continue
                    elif obs.step < 400 and unit["energy"] >= 100:
                        actions[uid] = trap_action
                        continue
                # Check if Factory is blocked
                factory_blocked = False
                factory_unit = None
                for fu in friendly_units.values():
                    if fu["type"] == 0:
                        factory_unit = fu
                        break

                if factory_unit:
                    paths = find_reachable_paths(
                        cartographer, (factory_unit["col"], factory_unit["row"]),
                        obs.step, obs.southBound, scroll_counter,
                        getattr(config, "factoryMovePeriod", 2), config, max_depth=10,
                        initial_jump_cd=factory_unit["jump_cd"],
                        safety_buffer=dynamic_safety_buffer,
                        blocked_cells=enemy_positions
                    )
                    has_forward_path = any(pos[1] > factory_unit["row"] for pos in paths.keys())
                    if not has_forward_path:
                        factory_blocked = True

                if factory_blocked and factory_unit:
                    blocking_info = self.find_blocking_wall(
                        cartographer, (factory_unit["col"], factory_unit["row"]), obs, config
                    )
                    if blocking_info:
                        wall_cell, direction = blocking_info
                        fx, fy = factory_unit["col"], factory_unit["row"]
                        if wall_cell == (fx, fy):
                            dc, dr = cartographer.DIR_OFFSETS[direction]
                            target_cell = (fx + dc, fy + dr)
                            opp_dir = {"NORTH": "SOUTH", "SOUTH": "NORTH", "EAST": "WEST", "WEST": "EAST"}[direction]
                            remove_action = f"REMOVE_{opp_dir}"
                        else:
                            target_cell = wall_cell
                            remove_action = f"REMOVE_{direction}"

                        if (col, row) == target_cell:
                            if obs.step < 400 and unit["energy"] >= 100:
                                actions[uid] = remove_action
                                # Worker stays stationary, current cell is already reserved
                                continue
                        else:
                            p = find_path(
                                cartographer, (col, row), target_cell,
                                obs.step, obs.southBound, scroll_counter,
                                move_period, config,
                                blocked_cells=enemy_positions
                            )
                            if p:
                                next_pos = p[0]
                                dx = next_pos[0] - col
                                dy = next_pos[1] - row
                                dir_to_move = None
                                if (dx, dy) == (0, 1):
                                    dir_to_move = "NORTH"
                                elif (dx, dy) == (0, -1):
                                    dir_to_move = "SOUTH"
                                elif (dx, dy) == (1, 0):
                                    dir_to_move = "EAST"
                                elif (dx, dy) == (-1, 0):
                                    dir_to_move = "WEST"

                                if dir_to_move and cartographer.is_walkable(col, row, dir_to_move):
                                    if next_pos not in reserved_cells:
                                        projected_south = project_south_bound(
                                            obs.step, obs.southBound, scroll_counter, move_period, config
                                        )
                                        if next_pos[1] >= projected_south:
                                            actions[uid] = dir_to_move
                                            self.unit_paths[uid] = p[1:]
                                            # Vacate old cell, reserve new cell
                                            if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                                                del reserved_cells[(col, row)]
                                            reserved_cells[next_pos] = uid
                                            continue
                elif uid in tactical_targets:
                    t_cell = tactical_targets[uid]
                    if (col, row) == t_cell:
                        actions[uid] = "IDLE"
                        continue
                    p = find_path(
                        cartographer, (col, row), t_cell,
                        obs.step, obs.southBound, scroll_counter,
                        move_period, config,
                        blocked_cells=enemy_positions
                    )
                    if p:
                        next_pos = p[0]
                        dx = next_pos[0] - col
                        dy = next_pos[1] - row
                        dir_to_move = None
                        if (dx, dy) == (0, 1):
                            dir_to_move = "NORTH"
                        elif (dx, dy) == (0, -1):
                            dir_to_move = "SOUTH"
                        elif (dx, dy) == (1, 0):
                            dir_to_move = "EAST"
                        elif (dx, dy) == (-1, 0):
                            dir_to_move = "WEST"

                        if dir_to_move and cartographer.is_walkable(col, row, dir_to_move):
                            if next_pos not in reserved_cells:
                                projected_south = project_south_bound(
                                    obs.step, obs.southBound, scroll_counter, move_period, config
                                )
                                if next_pos[1] >= projected_south:
                                    actions[uid] = dir_to_move
                                    self.unit_paths[uid] = p[1:]
                                    # Vacate old cell, reserve new cell
                                    if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                                        del reserved_cells[(col, row)]
                                    reserved_cells[next_pos] = uid
                                    continue

            # --- Default Pathfollowing / Searching ---
            path = self.unit_paths.get(uid)

            # Validate existing cached path
            if path:
                next_pos = path[0]
                dx = next_pos[0] - col
                dy = next_pos[1] - row
                direction = None
                is_jump = False
                if (dx, dy) == (0, 1):
                    direction = "NORTH"
                elif (dx, dy) == (0, -1):
                    direction = "SOUTH"
                elif (dx, dy) == (1, 0):
                    direction = "EAST"
                elif (dx, dy) == (-1, 0):
                    direction = "WEST"
                elif rtype == 0 and (dx, dy) == (0, 2):
                    direction = "JUMP_NORTH"
                    is_jump = True
                elif rtype == 0 and (dx, dy) == (0, -2):
                    direction = "JUMP_SOUTH"
                    is_jump = True
                elif rtype == 0 and (dx, dy) == (2, 0):
                    direction = "JUMP_EAST"
                    is_jump = True
                elif rtype == 0 and (dx, dy) == (-2, 0):
                    direction = "JUMP_WEST"
                    is_jump = True
                elif (dx, dy) == (0, 0):
                    direction = "IDLE"

                valid_move = False
                if direction:
                    if is_jump or direction == "IDLE":
                        valid_move = True
                    elif cartographer.is_walkable(col, row, direction):
                        valid_move = True

                if valid_move:
                    # Destination cell must not be reserved
                    if next_pos not in reserved_cells or reserved_cells[next_pos] == uid:
                        # Factory collision guard: only avoid collision when enemy has >= our energy
                        if rtype == 0 and next_pos in enemy_positions and enemy_factory_energy >= unit["energy"]:
                            self.unit_paths[uid] = None
                            # Fall through to re-pathing below
                        else:
                            # Factory South safety override (only applies to walking SOUTH)
                            if rtype == 0 and direction == "SOUTH":
                                if not is_seeking_mine and not is_chasing_enemy and jump_cd == 0 and row + 2 <= obs.northBound and (col, row + 2) not in reserved_cells:
                                    direction = "JUMP_NORTH"
                                    next_pos = (col, row + 2)
                                elif not is_seeking_mine and not is_chasing_enemy and next_pos[1] <= obs.southBound + dynamic_safety_buffer:
                                    direction = None

                            if direction:
                                projected_south = project_south_bound(
                                    obs.step, obs.southBound, scroll_counter, move_period, config
                                )
                                if next_pos[1] >= projected_south:
                                    actions[uid] = direction
                                    self.unit_paths[uid].pop(0)
                                    # Vacate old cell, reserve new cell
                                    if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                                        del reserved_cells[(col, row)]
                                    reserved_cells[next_pos] = uid
                                    continue
            # Path is invalid or blocked
            self.unit_paths[uid] = None
            path = None

            # Find a new path using A* / BFS
            if not path:
                best_path = None
                best_target = None

                if uid in tactical_targets:
                    t_cell = tactical_targets[uid]
                    if (col, row) == t_cell:
                        actions[uid] = "IDLE"
                        # Reserve current cell
                        if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                            pass
                        else:
                            reserved_cells[(col, row)] = uid
                        continue
                    initial_jcd = unit["jump_cd"] if rtype == 0 else None
                    p = find_path(
                        cartographer, (col, row), t_cell,
                        obs.step, obs.southBound, scroll_counter,
                        move_period, config,
                        initial_jump_cd=initial_jcd,
                        safety_buffer=(dynamic_safety_buffer if (rtype == 0 and not is_seeking_mine and not is_chasing_enemy) else 0),
                        blocked_cells=enemy_positions
                    )
                    if p:
                        best_path = p
                        best_target = t_cell

                if not best_path:
                    initial_jcd = unit["jump_cd"] if rtype == 0 else None
                    paths = find_reachable_paths(
                        cartographer, (col, row),
                        obs.step, obs.southBound, scroll_counter,
                        move_period, config, max_depth=self.max_depth,
                        initial_jump_cd=initial_jcd,
                        safety_buffer=(dynamic_safety_buffer if (rtype == 0 and not is_seeking_mine and not is_chasing_enemy) else 0),
                        blocked_cells=enemy_positions
                    )

                    # Check for reachable crystals (first step must be unreserved)
                    reachable_crystals = []
                    for key, val in obs.crystals.items():
                        try:
                            cc, cr = map(int, key.split(","))
                            if (cc, cr) in paths and paths[(cc, cr)]:
                                if rtype == 0 and cr <= row:
                                    continue
                                next_step = paths[(cc, cr)][0]
                                if next_step not in reserved_cells:
                                    reachable_crystals.append((cc, cr))
                        except ValueError:
                            pass

                    if reachable_crystals:
                        reachable_crystals.sort(key=lambda pos: len(paths[pos]))
                        best_target = reachable_crystals[0]
                        best_path = paths[best_target]
                    else:
                        # Target the northward cell with maximum row index
                        safe_nodes = []
                        for pos, p in paths.items():
                            if p and p[0] not in reserved_cells:
                                safe_nodes.append(pos)

                        if safe_nodes:
                            max_reachable_row = max(pos[1] for pos in safe_nodes)
                            if max_reachable_row > row:
                                candidates = [pos for pos in safe_nodes if pos[1] == max_reachable_row]
                                best_target = min(candidates, key=lambda pos: abs(pos[0] - col))
                                best_path = paths[best_target]

                if best_path:
                    self.unit_paths[uid] = list(best_path)
                    self.unit_targets[uid] = best_target
                    next_pos = best_path[0]

                    if next_pos in reserved_cells and reserved_cells[next_pos] != uid:
                        direction = None
                    else:
                        dx = next_pos[0] - col
                        dy = next_pos[1] - row
                        direction = None
                        is_jump = False
                        if (dx, dy) == (0, 1):
                            direction = "NORTH"
                        elif (dx, dy) == (0, -1):
                            direction = "SOUTH"
                        elif (dx, dy) == (1, 0):
                            direction = "EAST"
                        elif (dx, dy) == (-1, 0):
                            direction = "WEST"
                        elif rtype == 0 and (dx, dy) == (0, 2):
                            direction = "JUMP_NORTH"
                            is_jump = True
                        elif rtype == 0 and (dx, dy) == (0, -2):
                            direction = "JUMP_SOUTH"
                            is_jump = True
                        elif rtype == 0 and (dx, dy) == (2, 0):
                            direction = "JUMP_EAST"
                            is_jump = True
                        elif rtype == 0 and (dx, dy) == (-2, 0):
                            direction = "JUMP_WEST"
                            is_jump = True
                        elif (dx, dy) == (0, 0):
                            direction = "IDLE"

                        # Factory collision guard: only avoid when enemy has >= our energy
                        if rtype == 0 and next_pos in enemy_positions and enemy_factory_energy >= unit["energy"]:
                            direction = None

                        # Factory South safety override (only applies to walking SOUTH)
                        if rtype == 0 and direction == "SOUTH":
                            if not is_seeking_mine and not is_chasing_enemy and jump_cd == 0 and row + 2 <= obs.northBound and (col, row + 2) not in reserved_cells:
                                direction = "JUMP_NORTH"
                                next_pos = (col, row + 2)
                            elif not is_seeking_mine and not is_chasing_enemy and next_pos[1] <= obs.southBound + dynamic_safety_buffer:
                                direction = None

                        if direction:
                            actions[uid] = direction
                            self.unit_paths[uid].pop(0)
                            # Vacate old cell, reserve new cell
                            if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                                del reserved_cells[(col, row)]
                            reserved_cells[next_pos] = uid
                else:
                    # If the Factory has no path, do not pace or jump blindly.
                    # Standing still is safer than burning energy in a coordinate loop.
                    if rtype == 0:
                        actions[uid] = "IDLE"

                        # Handle spawn trap cancellation if this cell was reserved for a spawn
                        if (col, row) in reserved_cells:
                            owner_val = reserved_cells[(col, row)]
                            if isinstance(owner_val, str) and owner_val.startswith("SPAWN_"):
                                spawn_factory_uid = owner_val.split("_")[1]
                                actions[spawn_factory_uid] = "IDLE"
                                del reserved_cells[(col, row)]

                        reserved_cells[(col, row)] = uid
                        continue

                    # Fallback moves if no path is found
                    fallback_action = None
                    if row <= obs.southBound + dynamic_safety_buffer:
                        if not fallback_action:
                            # Find a free adjacent cell
                            for d in ["NORTH", "EAST", "WEST", "SOUTH"]:
                                if cartographer.is_walkable(col, row, d):
                                    dc, dr = cartographer.DIR_OFFSETS[d]
                                    nc, nr = col + dc, row + dr
                                    if (nc, nr) not in reserved_cells:
                                        # Factory South safety override for fallback
                                        if rtype == 0 and d == "SOUTH":
                                            if not is_seeking_mine and not is_chasing_enemy and jump_cd == 0 and row + 2 <= obs.northBound and (col, row + 2) not in reserved_cells:
                                                fallback_action = "JUMP_NORTH"
                                                if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                                                    del reserved_cells[(col, row)]
                                                reserved_cells[(col, row + 2)] = uid
                                                break
                                            elif not is_seeking_mine and not is_chasing_enemy and nr <= obs.southBound + dynamic_safety_buffer:
                                                continue

                                        if d == "SOUTH" and row <= obs.southBound + dynamic_safety_buffer:
                                            continue
                                        fallback_action = d
                                        if (col, row) in reserved_cells and reserved_cells[(col, row)] == uid:
                                            del reserved_cells[(col, row)]
                                        reserved_cells[(nc, nr)] = uid
                                        break

                    if fallback_action:
                        actions[uid] = fallback_action
                    else:
                        # Forced IDLE: reserve current cell
                        actions[uid] = "IDLE"

                        # Handle spawn trap cancellation if this cell was reserved for a spawn
                        if (col, row) in reserved_cells:
                            owner_val = reserved_cells[(col, row)]
                            if isinstance(owner_val, str) and owner_val.startswith("SPAWN_"):
                                spawn_factory_uid = owner_val.split("_")[1]
                                actions[spawn_factory_uid] = "IDLE"
                                del reserved_cells[(col, row)]

                        reserved_cells[(col, row)] = uid

        if not factory_reservations_broadcast:
            self._broadcast_factory_reservations(factory_uid, friendly_units, actions)

        # Debug Factory movement decisions
        for uid, unit in friendly_units.items():
            if unit["type"] == 0:
                print(f"DEBUG_FACTORY: Step {obs.step} pos: ({unit['col']},{unit['row']}) target: {self.unit_targets.get(uid)} path: {self.unit_paths.get(uid)} jump_cd: {unit['jump_cd']} action: {actions.get(uid)}", flush=True)
            elif unit["type"] == 1:
                print(f"DEBUG_SCOUT: Step {obs.step} uid: {uid[:4]} pos: ({unit['col']},{unit['row']}) energy: {unit['energy']} target: {self.unit_targets.get(uid)} path: {self.unit_paths.get(uid)}", flush=True)
            elif unit["type"] == 2:
                print(f"DEBUG_WORKER: Step {obs.step} uid: {uid[:4]} pos: ({unit['col']},{unit['row']}) energy: {unit['energy']} target: {self.unit_targets.get(uid)} path: {self.unit_paths.get(uid)} action: {actions.get(uid)}", flush=True)
            elif unit["type"] == 3:
                print(f"DEBUG_MINER: Step {obs.step} uid: {uid[:4]} pos: ({unit['col']},{unit['row']}) energy: {unit['energy']} target: {self.unit_targets.get(uid)} path: {self.unit_paths.get(uid)} action: {actions.get(uid)}", flush=True)

        self.last_turn_elapsed = time.time() - start_time
        return actions
# === End of orchestrator.py ===


# Persistent agent state
player_cartographers = {}
controllers = {}

def agent(obs, config):
    player = obs.player
    if player not in player_cartographers:
        player_cartographers[player] = Cartographer(width=config.width, height=config.height)
        controllers[player] = TrafficController(enable_tactics=True)
        
    cartographer = player_cartographers[player]
    controller = controllers[player]
    cartographer.update(obs)
    
    return controller.process_turn(obs, cartographer, config)

